version: "3"
services:

  postgres_db:
    build: ./Database
    container_name: postgres_tn
    environment:
      POSTGRES_DB: tn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  go-server:
    build: ./Server
    volumes:
      - ./Server:/app
    ports:
      - 8081:8081
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - postgres
    links:
      - postgres
    command: air

  react-client:
    container_name: react_tn
    build: ./Client
    volumes:
      - ./Client/src:/app/src
      - ./Client/public/assets:/app/public/assets
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    command: npm start
